name: Deploy Release

on:
  push:
    # Запускать этот workflow при пуше в ветку 'phprails' (или 'main', 'production', если у вас другая основная ветка)
    branches:
      - phprails

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory for release files
      run: |
        set -e
        mkdir temp_release_contents

    - name: Copy PHP files to temp directory
      run: |
        set -e
        cp *.php temp_release_contents/

    - name: Copy other root files to temp directory
      run: |
        set -e
        cp README.md temp_release_contents/
        cp restart_service.ps1 temp_release_contents/
        cp update_from_url.ps1 temp_release_contents/

    - name: Copy directories to temp directory
      run: |
        set -e
        cp -R templates temp_release_contents/
        cp -R settings_storage temp_release_contents/
        cp -R samples temp_release_contents/
        cp -R resource temp_release_contents/

    - name: Create ZIP archive
      run: |
        set -e
        cd temp_release_contents/
        zip -r ../release.zip ./*

    - name: Debug - List files in root after zip
      run: |
        ls -la ${{ github.workspace }}

    - name: Create dummy file
      run: echo "dummy content" > dummy.txt

    - name: Get current date for tag
      id: date
      run: |
        echo "TAG_DATE=$(date +'%Y_%m_%d_%H%M')" >> "$GITHUB_OUTPUT"

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.date.outputs.TAG_DATE }} # Тег релиза, например 2024_07_25_1030
        name: Release ${{ steps.date.outputs.TAG_DATE }} # Имя релиза
        draft: false # Установите true, если хотите создавать черновики релизов
        prerelease: false # Установите true, если это предварительный релиз
        files: |
          release.zip
          dummy.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Токен GitHub, предоставляется автоматически

    - name: Output Release URL
      run: 'echo "Release URL: ${{ steps.create_release.outputs.html_url }}"'